name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        jdk: [17]
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser

      - name: Enable Safari Remote Automation
        run: sudo /usr/bin/safaridriver --enable

      - name: Build and compile the project with debug output
        run: |
          mvn clean package -X > build-debug.log || true 

      - name: Display build log
        run: cat build-debug.log  # Zeigen Sie die Debug-Ausgabe zur Fehlersuche an.

      - name: Set execute permissions for test script
        run: chmod +x ./scripts/run_tests.sh

      - name: Run Java tests
        run: mvn test

      - name: Run additional tests
        run: ./scripts/run_tests.sh