name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 1
      matrix:
        jdk: [ 17 ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.jdk }}

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser  # Beispiel für macOS-spezifische Abhängigkeit

      - name: Run tests
        run: ./scripts/run_tests.sh  # Passe dies an, um dein Testskript auszuführen