name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        jdk: [ 17 ]
      max-parallel: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser
          brew install groovy

      - name: Build and compile the project
        run: |
          # Für Gradle-Projekte:
          # ./gradlew clean build
          # Für Maven-Projekte:
          mvn clean compile install

      - name: Run Groovy tests
        run: |
          # Setze den Klassenpfad und führe die Groovy-Tests aus
          for file in $(find src/test/groovy -name "*.groovy"); do
            groovy -cp target/classes:target/dependency/* $file
          done

      - name: Run additional tests
        run: ./scripts/run_tests.sh