name: Java CI with Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Ändere hier von macos-latest zu ubuntu-latest
    strategy:
      matrix:
        jdk: [17]
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Run Qodana Scan
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        run: |
          docker run --rm -e QODANA_TOKEN=$QODANA_TOKEN -v $(pwd):/data jetbrains/qodana-jvm --show-report

      - name: Build and compile the project with debug output
        run: |
          mvn clean package -X > build-debug.log || true

      - name: Display build log
        run: cat build-debug.log

      - name: Set execute permissions for test script
        run: chmod +x ./scripts/run_tests.sh

      - name: Run Java tests
        run: mvn test

      - name: Run additional tests
        run: ./scripts/run_tests.sh