name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        jdk: [ 17 ]
      max-parallel: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser
          # Weitere Homebrew-Installationen hier hinzufügen, falls benötigt

      - name: Build and compile the project
        run: |
          mvn clean compile dependency:copy-dependencies
          # Falls du Gradle verwendest, statt Maven:
          # ./gradlew clean build

      - name: Run Java tests
        run: mvn test

      - name: Run additional tests
        run: ./scripts/run_tests.sh