name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        jdk: [17]
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser
          brew upgrade

      - name: Enable Safari Remote Automation
        run: sudo /usr/bin/safaridriver --enable

      - name: Check macOS and Safari versions
        run: |
          sw_vers
          /usr/bin/safaridriver --version

      - name: Test SafariDriver Setup
        run: |
          echo "Testing SafariDriver..."
          echo "Open SafariDriver"
          /usr/bin/safaridriver --enable
          echo "Create a new Safari session"
          curl -X POST http://localhost:4444/wd/hub/session -H "Content-Type: application/json" -d '{"capabilities": {"alwaysMatch": {"browserName": "safari"}}}'

      - name: Build and compile the project with debug output
        run: |
          mvn clean package -X > build-debug.log || true 

      - name: Display build log
        run: cat build-debug.log

      - name: Upload build log
        uses: actions/upload-artifact@v3
        with:
          name: build-debug-log
          path: build-debug.log

      - name: Set execute permissions for test script
        run: chmod +x ./scripts/run_tests.sh

      - name: Run Java tests
        run: mvn test

      - name: Run additional tests
        run: ./scripts/run_tests.sh