name: Java CI with macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        jdk: [17]
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qodana
        uses: JetBrains/qodana-action@v2024.1
        with:
          token: ${{ secrets.QODANA_TOKEN }}

      - name: Run Qodana Scan
        run: qodana scan --show-report

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install defaultbrowser  # Verifizieren Sie, ob dieses Paket benötigt wird und ob es korrekt ist.

      - name: Build and compile the project with debug output
        run: |
          mvn clean package -X > build-debug.log || true  # Speichern Sie die detaillierte Debug-Ausgabe in einer Datei.

      - name: Display build log
        run: cat build-debug.log  # Zeigen Sie die Debug-Ausgabe zur Fehlersuche an.

      - name: Set execute permissions for test script
        run: chmod +x ./scripts/run_tests.sh

      - name: Run Java tests
        run: mvn test

      - name: Run additional tests
        run: ./scripts/run_tests.sh